config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'users#show'
  resources :users do
    resources :vehicles
  end

  resources :locations do
    resources :slots
  end

end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :slots
  # Validaciones
  validates :latitude, :longitude, presence: true, numericality: true
end

app/models/park_record.rb
class ParkRecord < ActiveRecord::Base
  belongs_to :vehicle
  belongs_to :slot
end

app/models/slot.rb
class Slot < ActiveRecord::Base
  belongs_to :location
  has_many :park_records
  has_many :vehicles, through: :park_records
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  # Relaciones
  has_many :vehicles
  # Validaciones
  validates :email, uniqueness: true ,on: :create, presence: true
  validates_format_of :email, with: Devise.email_regexp
  before_save :primera_mayuscula

  def primera_mayuscula
    if @first_name.capitalize!.nil? && @last_name.capitalize!.nil?
      @errors.messages[:first_name] = 'La primera letra debe ser mayuscula'
      @errors.messages[:last_name] = 'La primera letra debe ser mayuscula'
      return false
    else
      return true
    end
  end
end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
  # Definicion de las realaciones
  belongs_to :user
  has_many :park_records
  has_many :slots, through: :park_records
  # Validaciones
  validates
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/locations_controller.rb
class LocationsController < AplicationController
  def index
    @locations = Location.all
    flash[:error] = 'No locations registered.' if @locations.empty?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
  end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  def new
    @vehicle = Vehicle.new
    @user = current_user
  end

  def create
    @vehicle = Vehicle.new(vehicle_params)
    @vehicle.user_id = current_user.id
    if @vehicle.save
      flash[:succes] = 'Vehicle registered sucessfully'
      redirect_to user_vehicles_path(current_user)
    else
      flash[:error] = @vehicle.errors.full:messages.join(',')
      render 'new'
    end
  end

  def index
    @vehicles = current_user.vehicles
    @user = current_user
  end

  def vehicle_params
    params.require(:vehicle).permit(:user_id, :model, :year, :vin, :id)
  end
  private :vehicle_params
end

app/helpers/application_helper.rb
module ApplicationHelper
  def alert_class_for(flash_type)
    {
      :success =>  'alert-success',
      :error => 'alert-danger',
      :alert => 'alert-warning',
      :notice => 'alert-info'
    }[flash_type.to_sym] || flash_type.to_s
  end
end

app/helpers/vehicle_helper.rb
module VehicleHelper
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= alert_class_for(type) %> alert-dismissible fade in">
    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
    <%= message %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Síganos en <a href="https://twitter.com/?lang=es">Twitter</a>
    y <a href="https://www.facebook.com/">Facebook</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "Acerca De",   '#' %></li>
      <li><%= link_to "Contáctenos", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">

        <p class="navbar-text pull-right">
        <% if user_signed_in? %>
          Logged in as <strong><%= current_user.email %></strong>.
          <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
          <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        <% else %>
          <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
          <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
        <% end %>

      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_user_menu.html.erb
<!-- Single button -->
<div class="btn-group">
  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Menu <span class="caret"></span>
  </button>
  <ul class="dropdown-menu">
    <li><%= link_to "Vehicles", user_vehicles_path(current_user)%></li>
    <li><%= link_to "Reservations" %></li>
    <li><%= link_to "Account" %></li>
    <% if current_user.is_admin? %>
      <li><%= link_to "Users", users_path%></li>
      <li><%= link_to "Locations", locations_path%></li>
      <li><%= link_to "Settings" %></li>
      <li><%= link_to "History" %></li>
    <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ParkingSystem</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/locations/index.html.erb
<div class="row">
  <div class="table">
    <div class="que perezaaaa">

    </div>
  </div>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-2">
    <%= render partial: "layouts/user_menu" %>
  </div>
  <div class="col-md-8">
    <div class="row">

    </div>
    <div class="col-md-2">

    </div>
  </div>
</div>

app/views/vehicles/new.html.erb
<div class="row" >
  <div class="col-md-3">
  </div>
  <div class="col-md-6">
    <h3 class="text-center"> New Vehicle for <%= @user.first_name %> <%= @user.last_name %></h3>
  </div>
  <div class="col-md-3">
  </div>
</div>
<div class="row">
  <div class="col-md-3">
  </div>
  <div class="col-md-6">
    <%= form_for @vehicle, url: {action: 'create'} do |form|%>
      <div class="row">
        <div class="col-md-6">
          <%= form.label :model, for:'model'%>
        </div>
        <div class="col-md-6">
          <div class="form-group">
            <%= form.text_field :model, class:'form-control', required: true%>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-6">
          <%= form.label :year %>
        </div>
        <div class="col-md-6">
          <div class="form-group">
            <%= form.select :year, (Time.zone.now.year - 100)..(Time.zone.now.year), class: 'form-control', required: true %>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-6">
          <%= form.label :vin %>
        </div>
        <div class="col-md-6">
          <div class="form-group">
            <%= form.text_field :vin, required: true, class: 'form-control' %>
          </div>
        </div>
      </div>

      <div class="form-group">
        <%= form.submit "Register Vehicle", class: 'btn btn-success'%>
        <%= link_to "Cancel", user_vehicles_path(@user), class: 'btn btn-default'%>
      </div>
    <% end %>
  </div>
  <div class="col-md-3">
  </div>
</div>